### ISSUE TITLE
What type of SSD should I choose to test the performance of Bam

### ISSUE THREAD

**Issue by smallgrape14** [ZaidQureshi/bam#34]
Hello, I would like to ask if I want to reproduce the experiment in the BAM paper, is there any restriction on the SSD model used in the experiment? 
- What type of SSD is recommended?
- I hope the price of SSD will be more affordable compared to Intel Optane P5800x. 
- Can I choose Samsung 980 pro SSD to reproduce the experiment shown in the following figure in the paper?
![image](https://github.com/ZaidQureshi/bam/assets/60038680/2b938f99-6f53-4953-8770-9e039137768f)
Thank you !

**Comment by msharmavikram** [comment]
Yes for 980pro

**Comment by smallgrape14** [comment]
Thank you very much ！ ！！

**Comment by smallgrape14** [comment]
@msharmavikram ，Is it right to use nvm-block-bench to reproduce the experimental results in the paper BaM vs GDS as shown below?
![image](https://github.com/ZaidQureshi/bam/assets/60038680/daba1fb9-6bec-4a90-af49-dde48bc2e35d)

**Comment by msharmavikram** [comment]
nvm-block-bench can only generate data for BaM and not GDS. You need to write your own app for generating GDS data.

**Comment by smallgrape14** [comment]
My expression may not be clear.
What I mean is whether nvm-block-bench can be used to test the effective bandwidth of bam in this comparative experiment as shown above.
Thank you very much ! ! !

**Comment by smallgrape14** [comment]
I use the nvm-block-bench to test the bam 
- SSD used:  Samsung 980 pro 1TB
- GPU name: NVIDIA V100-PCIE-32GB

my test script is :
```
for i in 512 1024 2048 4096 8192 16384 32768 65536 
do 
     // Sequential Read
     sudo ./bin/nvm-block-bench --page_size=$i --threads=262144 --pages=262144 --reqs=1 --blk_size=64 --queue_depth=1024 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=135 --random=false
     // Random Read
     sudo ./bin/nvm-block-bench --page_size=$i --threads=262144 --pages=262144 --reqs=1 --blk_size=64 --queue_depth=1024 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=135 --random=true
done
```
the result figure is below:
![image](https://github.com/ZaidQureshi/bam/assets/60038680/1833dff7-b2c9-447d-92d4-8a8a46d2ebe2)
why is the result so strange ?  
@msharmavikram Have you ever done a similar test on Samsung 980 pro SSD? Do you know the reason for this result?
Looking forward to your answer, thank you

**Comment by msharmavikram** [comment]
Instead of plotting the bandwidth, recommend plotting IOPs. 

The plot you are showing might be result of several unknown reasons that it not possible to determine. To me a few. 

1. Your system configuration is not well calibrated. If I recall 980pro is gen4 SSD and GPU is gen3. The default parameters (like launch bounds and occupancy used in the nvmblockbench kernel are not calibrated sufficiently and correctly for given IO size.
2. GPUs and ssds are not in the same numa domain And not in the same PCIe tree going over PCIe switch. (If the path takes CPU, then we have issues like this as cpus usually are not great handling IOPs driven devices). 
3. Ssd is not warmed up correctly. You need to write couple of times fully before doing any sort of benchmarking. 

I hope this helps. These are quick ones that I can think off.

**Comment by smallgrape14** [comment]
hello, thank you very much 
> The default parameters (like launch bounds and occupancy used in the nvmblockbench kernel are not calibrated sufficiently and correctly for given IO size.

Do you mean that parameters like "threads" and "pages" in nvm-block-bench should also change as the IO size (page size) varies?

**Comment by msharmavikram** [comment]
Yes and also you will require to modify the code as lauch bound is a compile time argument that defines the occupancy. 

Please note, this should be tried after you are 100% certain that the system is right configuration space. Step 2 is very fundamental.
